name: Build and deploy Node.js app to Azure Web App - CSMF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Prepare deploy folder with dependencies
        run: |
          mkdir deploy
          cp index.js db.js package.json package-lock.json deploy/
          cp -r routes controllers deploy/
          cd deploy
          npm ci --production
          cd ..

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D43FE9820464A3081163C20D318D4B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_44D54444047B48A1A77603A311139408 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4CCD5D195094017B34693617226C854 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CSMF'
          slot-name: 'Production'
          package: deploy
#redploy