name: Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install mssql (and other deps)
        run: npm install mssql  # Explicitly installs the missing module

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D43FE9820464A3081163C20D318D4B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_44D54444047B48A1A77603A311139408 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4CCD5D195094017B34693617226C854 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CSMF'
          package: .  # Deploys the entire repo (with node_modules)